name: Generate Streak Stats

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v5

      - name: Generate Streak Stats
        uses: muhammad-fiaz/github-readme-streak-stats@v1.0.1
        with:
          USERNAME: ${{ github.repository_owner }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          THEME: catppuccin-mocha
          RING: fab387
          CURR_STREAK_NUM: f9e2af
          FIRE: fab387
          OUTPUT_PATH: github-streak-stats.svg

      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v4.2.0
        with:
          target_branch: output
          build_dir: .
          keep_history: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
